package com.school.course_achievement.mapper;

import com.school.course_achievement.pojo.Weight;
import com.school.course_achievement.pojo.WeightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int countByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int deleteByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int deleteByPrimaryKey(String kNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int insert(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int insertSelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    List<Weight> selectByExample(WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    Weight selectByPrimaryKey(String kNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int updateByExampleSelective(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int updateByExample(@Param("record") Weight record, @Param("example") WeightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int updateByPrimaryKeySelective(Weight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    int updateByPrimaryKey(Weight record);
}