package com.school.course_achievement.pojo;

public class ClassDegree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.k_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private String kNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.c_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_behave_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dBehaveAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_behave_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dBehaveLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_behave_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dBehaveHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_homework_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dHomeworkAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_homework_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dHomeworkLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_homework_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dHomeworkHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_test_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTestAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_test_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTestLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_test_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTestHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_final_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dFinalAvg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_final_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dFinalLow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_final_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dFinalHigh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_1_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget1Avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_2_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget2Avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_3_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget3Avg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_1_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget1O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_2_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget2O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_3_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget3O;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_total_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTotalO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_1_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget1F;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_2_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget2F;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_target_3_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTarget3F;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.d_total_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double dTotalF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.k_analyse
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private String kAnalyse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.k_improvement
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private String kImprovement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_degree.k_suggestion
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private String kSuggestion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.k_no
     *
     * @return the value of class_degree.k_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public String getkNo() {
        return kNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.k_no
     *
     * @param kNo the value for class_degree.k_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setkNo(String kNo) {
        this.kNo = kNo == null ? null : kNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.c_no
     *
     * @return the value of class_degree.c_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.c_no
     *
     * @param cNo the value for class_degree.c_no
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_behave_avg
     *
     * @return the value of class_degree.d_behave_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdBehaveAvg() {
        return dBehaveAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_behave_avg
     *
     * @param dBehaveAvg the value for class_degree.d_behave_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdBehaveAvg(Double dBehaveAvg) {
        this.dBehaveAvg = dBehaveAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_behave_low
     *
     * @return the value of class_degree.d_behave_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdBehaveLow() {
        return dBehaveLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_behave_low
     *
     * @param dBehaveLow the value for class_degree.d_behave_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdBehaveLow(Double dBehaveLow) {
        this.dBehaveLow = dBehaveLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_behave_high
     *
     * @return the value of class_degree.d_behave_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdBehaveHigh() {
        return dBehaveHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_behave_high
     *
     * @param dBehaveHigh the value for class_degree.d_behave_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdBehaveHigh(Double dBehaveHigh) {
        this.dBehaveHigh = dBehaveHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_homework_avg
     *
     * @return the value of class_degree.d_homework_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdHomeworkAvg() {
        return dHomeworkAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_homework_avg
     *
     * @param dHomeworkAvg the value for class_degree.d_homework_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdHomeworkAvg(Double dHomeworkAvg) {
        this.dHomeworkAvg = dHomeworkAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_homework_low
     *
     * @return the value of class_degree.d_homework_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdHomeworkLow() {
        return dHomeworkLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_homework_low
     *
     * @param dHomeworkLow the value for class_degree.d_homework_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdHomeworkLow(Double dHomeworkLow) {
        this.dHomeworkLow = dHomeworkLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_homework_high
     *
     * @return the value of class_degree.d_homework_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdHomeworkHigh() {
        return dHomeworkHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_homework_high
     *
     * @param dHomeworkHigh the value for class_degree.d_homework_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdHomeworkHigh(Double dHomeworkHigh) {
        this.dHomeworkHigh = dHomeworkHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_test_avg
     *
     * @return the value of class_degree.d_test_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTestAvg() {
        return dTestAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_test_avg
     *
     * @param dTestAvg the value for class_degree.d_test_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTestAvg(Double dTestAvg) {
        this.dTestAvg = dTestAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_test_low
     *
     * @return the value of class_degree.d_test_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTestLow() {
        return dTestLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_test_low
     *
     * @param dTestLow the value for class_degree.d_test_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTestLow(Double dTestLow) {
        this.dTestLow = dTestLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_test_high
     *
     * @return the value of class_degree.d_test_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTestHigh() {
        return dTestHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_test_high
     *
     * @param dTestHigh the value for class_degree.d_test_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTestHigh(Double dTestHigh) {
        this.dTestHigh = dTestHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_final_avg
     *
     * @return the value of class_degree.d_final_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdFinalAvg() {
        return dFinalAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_final_avg
     *
     * @param dFinalAvg the value for class_degree.d_final_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdFinalAvg(Double dFinalAvg) {
        this.dFinalAvg = dFinalAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_final_low
     *
     * @return the value of class_degree.d_final_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdFinalLow() {
        return dFinalLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_final_low
     *
     * @param dFinalLow the value for class_degree.d_final_low
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdFinalLow(Double dFinalLow) {
        this.dFinalLow = dFinalLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_final_high
     *
     * @return the value of class_degree.d_final_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdFinalHigh() {
        return dFinalHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_final_high
     *
     * @param dFinalHigh the value for class_degree.d_final_high
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdFinalHigh(Double dFinalHigh) {
        this.dFinalHigh = dFinalHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_1_avg
     *
     * @return the value of class_degree.d_target_1_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget1Avg() {
        return dTarget1Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_1_avg
     *
     * @param dTarget1Avg the value for class_degree.d_target_1_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget1Avg(Double dTarget1Avg) {
        this.dTarget1Avg = dTarget1Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_2_avg
     *
     * @return the value of class_degree.d_target_2_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget2Avg() {
        return dTarget2Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_2_avg
     *
     * @param dTarget2Avg the value for class_degree.d_target_2_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget2Avg(Double dTarget2Avg) {
        this.dTarget2Avg = dTarget2Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_3_avg
     *
     * @return the value of class_degree.d_target_3_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget3Avg() {
        return dTarget3Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_3_avg
     *
     * @param dTarget3Avg the value for class_degree.d_target_3_avg
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget3Avg(Double dTarget3Avg) {
        this.dTarget3Avg = dTarget3Avg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_1_o
     *
     * @return the value of class_degree.d_target_1_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget1O() {
        return dTarget1O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_1_o
     *
     * @param dTarget1O the value for class_degree.d_target_1_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget1O(Double dTarget1O) {
        this.dTarget1O = dTarget1O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_2_o
     *
     * @return the value of class_degree.d_target_2_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget2O() {
        return dTarget2O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_2_o
     *
     * @param dTarget2O the value for class_degree.d_target_2_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget2O(Double dTarget2O) {
        this.dTarget2O = dTarget2O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_3_o
     *
     * @return the value of class_degree.d_target_3_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget3O() {
        return dTarget3O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_3_o
     *
     * @param dTarget3O the value for class_degree.d_target_3_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget3O(Double dTarget3O) {
        this.dTarget3O = dTarget3O;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_total_o
     *
     * @return the value of class_degree.d_total_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTotalO() {
        return dTotalO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_total_o
     *
     * @param dTotalO the value for class_degree.d_total_o
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTotalO(Double dTotalO) {
        this.dTotalO = dTotalO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_1_f
     *
     * @return the value of class_degree.d_target_1_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget1F() {
        return dTarget1F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_1_f
     *
     * @param dTarget1F the value for class_degree.d_target_1_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget1F(Double dTarget1F) {
        this.dTarget1F = dTarget1F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_2_f
     *
     * @return the value of class_degree.d_target_2_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget2F() {
        return dTarget2F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_2_f
     *
     * @param dTarget2F the value for class_degree.d_target_2_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget2F(Double dTarget2F) {
        this.dTarget2F = dTarget2F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_target_3_f
     *
     * @return the value of class_degree.d_target_3_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTarget3F() {
        return dTarget3F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_target_3_f
     *
     * @param dTarget3F the value for class_degree.d_target_3_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTarget3F(Double dTarget3F) {
        this.dTarget3F = dTarget3F;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.d_total_f
     *
     * @return the value of class_degree.d_total_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getdTotalF() {
        return dTotalF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.d_total_f
     *
     * @param dTotalF the value for class_degree.d_total_f
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setdTotalF(Double dTotalF) {
        this.dTotalF = dTotalF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.k_analyse
     *
     * @return the value of class_degree.k_analyse
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public String getkAnalyse() {
        return kAnalyse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.k_analyse
     *
     * @param kAnalyse the value for class_degree.k_analyse
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setkAnalyse(String kAnalyse) {
        this.kAnalyse = kAnalyse == null ? null : kAnalyse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.k_improvement
     *
     * @return the value of class_degree.k_improvement
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public String getkImprovement() {
        return kImprovement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.k_improvement
     *
     * @param kImprovement the value for class_degree.k_improvement
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setkImprovement(String kImprovement) {
        this.kImprovement = kImprovement == null ? null : kImprovement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_degree.k_suggestion
     *
     * @return the value of class_degree.k_suggestion
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public String getkSuggestion() {
        return kSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_degree.k_suggestion
     *
     * @param kSuggestion the value for class_degree.k_suggestion
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setkSuggestion(String kSuggestion) {
        this.kSuggestion = kSuggestion == null ? null : kSuggestion.trim();
    }
}