package com.school.course_achievement.pojo;

import java.util.ArrayList;
import java.util.List;

public class ClassDegreeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public ClassDegreeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKNoIsNull() {
            addCriterion("k_no is null");
            return (Criteria) this;
        }

        public Criteria andKNoIsNotNull() {
            addCriterion("k_no is not null");
            return (Criteria) this;
        }

        public Criteria andKNoEqualTo(String value) {
            addCriterion("k_no =", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotEqualTo(String value) {
            addCriterion("k_no <>", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoGreaterThan(String value) {
            addCriterion("k_no >", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoGreaterThanOrEqualTo(String value) {
            addCriterion("k_no >=", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLessThan(String value) {
            addCriterion("k_no <", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLessThanOrEqualTo(String value) {
            addCriterion("k_no <=", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLike(String value) {
            addCriterion("k_no like", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotLike(String value) {
            addCriterion("k_no not like", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoIn(List<String> values) {
            addCriterion("k_no in", values, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotIn(List<String> values) {
            addCriterion("k_no not in", values, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoBetween(String value1, String value2) {
            addCriterion("k_no between", value1, value2, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotBetween(String value1, String value2) {
            addCriterion("k_no not between", value1, value2, "kNo");
            return (Criteria) this;
        }

        public Criteria andCNoIsNull() {
            addCriterion("c_no is null");
            return (Criteria) this;
        }

        public Criteria andCNoIsNotNull() {
            addCriterion("c_no is not null");
            return (Criteria) this;
        }

        public Criteria andCNoEqualTo(String value) {
            addCriterion("c_no =", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoNotEqualTo(String value) {
            addCriterion("c_no <>", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoGreaterThan(String value) {
            addCriterion("c_no >", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoGreaterThanOrEqualTo(String value) {
            addCriterion("c_no >=", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoLessThan(String value) {
            addCriterion("c_no <", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoLessThanOrEqualTo(String value) {
            addCriterion("c_no <=", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoLike(String value) {
            addCriterion("c_no like", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoNotLike(String value) {
            addCriterion("c_no not like", value, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoIn(List<String> values) {
            addCriterion("c_no in", values, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoNotIn(List<String> values) {
            addCriterion("c_no not in", values, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoBetween(String value1, String value2) {
            addCriterion("c_no between", value1, value2, "cNo");
            return (Criteria) this;
        }

        public Criteria andCNoNotBetween(String value1, String value2) {
            addCriterion("c_no not between", value1, value2, "cNo");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgIsNull() {
            addCriterion("d_behave_avg is null");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgIsNotNull() {
            addCriterion("d_behave_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgEqualTo(Double value) {
            addCriterion("d_behave_avg =", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgNotEqualTo(Double value) {
            addCriterion("d_behave_avg <>", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgGreaterThan(Double value) {
            addCriterion("d_behave_avg >", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_behave_avg >=", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgLessThan(Double value) {
            addCriterion("d_behave_avg <", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgLessThanOrEqualTo(Double value) {
            addCriterion("d_behave_avg <=", value, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgIn(List<Double> values) {
            addCriterion("d_behave_avg in", values, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgNotIn(List<Double> values) {
            addCriterion("d_behave_avg not in", values, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgBetween(Double value1, Double value2) {
            addCriterion("d_behave_avg between", value1, value2, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveAvgNotBetween(Double value1, Double value2) {
            addCriterion("d_behave_avg not between", value1, value2, "dBehaveAvg");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowIsNull() {
            addCriterion("d_behave_low is null");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowIsNotNull() {
            addCriterion("d_behave_low is not null");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowEqualTo(Double value) {
            addCriterion("d_behave_low =", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowNotEqualTo(Double value) {
            addCriterion("d_behave_low <>", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowGreaterThan(Double value) {
            addCriterion("d_behave_low >", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowGreaterThanOrEqualTo(Double value) {
            addCriterion("d_behave_low >=", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowLessThan(Double value) {
            addCriterion("d_behave_low <", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowLessThanOrEqualTo(Double value) {
            addCriterion("d_behave_low <=", value, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowIn(List<Double> values) {
            addCriterion("d_behave_low in", values, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowNotIn(List<Double> values) {
            addCriterion("d_behave_low not in", values, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowBetween(Double value1, Double value2) {
            addCriterion("d_behave_low between", value1, value2, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveLowNotBetween(Double value1, Double value2) {
            addCriterion("d_behave_low not between", value1, value2, "dBehaveLow");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighIsNull() {
            addCriterion("d_behave_high is null");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighIsNotNull() {
            addCriterion("d_behave_high is not null");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighEqualTo(Double value) {
            addCriterion("d_behave_high =", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighNotEqualTo(Double value) {
            addCriterion("d_behave_high <>", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighGreaterThan(Double value) {
            addCriterion("d_behave_high >", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighGreaterThanOrEqualTo(Double value) {
            addCriterion("d_behave_high >=", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighLessThan(Double value) {
            addCriterion("d_behave_high <", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighLessThanOrEqualTo(Double value) {
            addCriterion("d_behave_high <=", value, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighIn(List<Double> values) {
            addCriterion("d_behave_high in", values, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighNotIn(List<Double> values) {
            addCriterion("d_behave_high not in", values, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighBetween(Double value1, Double value2) {
            addCriterion("d_behave_high between", value1, value2, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDBehaveHighNotBetween(Double value1, Double value2) {
            addCriterion("d_behave_high not between", value1, value2, "dBehaveHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgIsNull() {
            addCriterion("d_homework_avg is null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgIsNotNull() {
            addCriterion("d_homework_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgEqualTo(Double value) {
            addCriterion("d_homework_avg =", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgNotEqualTo(Double value) {
            addCriterion("d_homework_avg <>", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgGreaterThan(Double value) {
            addCriterion("d_homework_avg >", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_homework_avg >=", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgLessThan(Double value) {
            addCriterion("d_homework_avg <", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgLessThanOrEqualTo(Double value) {
            addCriterion("d_homework_avg <=", value, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgIn(List<Double> values) {
            addCriterion("d_homework_avg in", values, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgNotIn(List<Double> values) {
            addCriterion("d_homework_avg not in", values, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgBetween(Double value1, Double value2) {
            addCriterion("d_homework_avg between", value1, value2, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkAvgNotBetween(Double value1, Double value2) {
            addCriterion("d_homework_avg not between", value1, value2, "dHomeworkAvg");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowIsNull() {
            addCriterion("d_homework_low is null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowIsNotNull() {
            addCriterion("d_homework_low is not null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowEqualTo(Double value) {
            addCriterion("d_homework_low =", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowNotEqualTo(Double value) {
            addCriterion("d_homework_low <>", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowGreaterThan(Double value) {
            addCriterion("d_homework_low >", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowGreaterThanOrEqualTo(Double value) {
            addCriterion("d_homework_low >=", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowLessThan(Double value) {
            addCriterion("d_homework_low <", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowLessThanOrEqualTo(Double value) {
            addCriterion("d_homework_low <=", value, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowIn(List<Double> values) {
            addCriterion("d_homework_low in", values, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowNotIn(List<Double> values) {
            addCriterion("d_homework_low not in", values, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowBetween(Double value1, Double value2) {
            addCriterion("d_homework_low between", value1, value2, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkLowNotBetween(Double value1, Double value2) {
            addCriterion("d_homework_low not between", value1, value2, "dHomeworkLow");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighIsNull() {
            addCriterion("d_homework_high is null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighIsNotNull() {
            addCriterion("d_homework_high is not null");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighEqualTo(Double value) {
            addCriterion("d_homework_high =", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighNotEqualTo(Double value) {
            addCriterion("d_homework_high <>", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighGreaterThan(Double value) {
            addCriterion("d_homework_high >", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighGreaterThanOrEqualTo(Double value) {
            addCriterion("d_homework_high >=", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighLessThan(Double value) {
            addCriterion("d_homework_high <", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighLessThanOrEqualTo(Double value) {
            addCriterion("d_homework_high <=", value, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighIn(List<Double> values) {
            addCriterion("d_homework_high in", values, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighNotIn(List<Double> values) {
            addCriterion("d_homework_high not in", values, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighBetween(Double value1, Double value2) {
            addCriterion("d_homework_high between", value1, value2, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDHomeworkHighNotBetween(Double value1, Double value2) {
            addCriterion("d_homework_high not between", value1, value2, "dHomeworkHigh");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgIsNull() {
            addCriterion("d_test_1_avg is null");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgIsNotNull() {
            addCriterion("d_test_1_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgEqualTo(Double value) {
            addCriterion("d_test_1_avg =", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgNotEqualTo(Double value) {
            addCriterion("d_test_1_avg <>", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgGreaterThan(Double value) {
            addCriterion("d_test_1_avg >", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_test_1_avg >=", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgLessThan(Double value) {
            addCriterion("d_test_1_avg <", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgLessThanOrEqualTo(Double value) {
            addCriterion("d_test_1_avg <=", value, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgIn(List<Double> values) {
            addCriterion("d_test_1_avg in", values, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgNotIn(List<Double> values) {
            addCriterion("d_test_1_avg not in", values, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgBetween(Double value1, Double value2) {
            addCriterion("d_test_1_avg between", value1, value2, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1AvgNotBetween(Double value1, Double value2) {
            addCriterion("d_test_1_avg not between", value1, value2, "dTest1Avg");
            return (Criteria) this;
        }

        public Criteria andDTest1LowIsNull() {
            addCriterion("d_test_1_low is null");
            return (Criteria) this;
        }

        public Criteria andDTest1LowIsNotNull() {
            addCriterion("d_test_1_low is not null");
            return (Criteria) this;
        }

        public Criteria andDTest1LowEqualTo(Double value) {
            addCriterion("d_test_1_low =", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowNotEqualTo(Double value) {
            addCriterion("d_test_1_low <>", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowGreaterThan(Double value) {
            addCriterion("d_test_1_low >", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowGreaterThanOrEqualTo(Double value) {
            addCriterion("d_test_1_low >=", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowLessThan(Double value) {
            addCriterion("d_test_1_low <", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowLessThanOrEqualTo(Double value) {
            addCriterion("d_test_1_low <=", value, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowIn(List<Double> values) {
            addCriterion("d_test_1_low in", values, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowNotIn(List<Double> values) {
            addCriterion("d_test_1_low not in", values, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowBetween(Double value1, Double value2) {
            addCriterion("d_test_1_low between", value1, value2, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1LowNotBetween(Double value1, Double value2) {
            addCriterion("d_test_1_low not between", value1, value2, "dTest1Low");
            return (Criteria) this;
        }

        public Criteria andDTest1HighIsNull() {
            addCriterion("d_test_1_high is null");
            return (Criteria) this;
        }

        public Criteria andDTest1HighIsNotNull() {
            addCriterion("d_test_1_high is not null");
            return (Criteria) this;
        }

        public Criteria andDTest1HighEqualTo(Double value) {
            addCriterion("d_test_1_high =", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighNotEqualTo(Double value) {
            addCriterion("d_test_1_high <>", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighGreaterThan(Double value) {
            addCriterion("d_test_1_high >", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighGreaterThanOrEqualTo(Double value) {
            addCriterion("d_test_1_high >=", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighLessThan(Double value) {
            addCriterion("d_test_1_high <", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighLessThanOrEqualTo(Double value) {
            addCriterion("d_test_1_high <=", value, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighIn(List<Double> values) {
            addCriterion("d_test_1_high in", values, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighNotIn(List<Double> values) {
            addCriterion("d_test_1_high not in", values, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighBetween(Double value1, Double value2) {
            addCriterion("d_test_1_high between", value1, value2, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDTest1HighNotBetween(Double value1, Double value2) {
            addCriterion("d_test_1_high not between", value1, value2, "dTest1High");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgIsNull() {
            addCriterion("d_final_avg is null");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgIsNotNull() {
            addCriterion("d_final_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgEqualTo(Double value) {
            addCriterion("d_final_avg =", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgNotEqualTo(Double value) {
            addCriterion("d_final_avg <>", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgGreaterThan(Double value) {
            addCriterion("d_final_avg >", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_final_avg >=", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgLessThan(Double value) {
            addCriterion("d_final_avg <", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgLessThanOrEqualTo(Double value) {
            addCriterion("d_final_avg <=", value, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgIn(List<Double> values) {
            addCriterion("d_final_avg in", values, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgNotIn(List<Double> values) {
            addCriterion("d_final_avg not in", values, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgBetween(Double value1, Double value2) {
            addCriterion("d_final_avg between", value1, value2, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalAvgNotBetween(Double value1, Double value2) {
            addCriterion("d_final_avg not between", value1, value2, "dFinalAvg");
            return (Criteria) this;
        }

        public Criteria andDFinalLowIsNull() {
            addCriterion("d_final_low is null");
            return (Criteria) this;
        }

        public Criteria andDFinalLowIsNotNull() {
            addCriterion("d_final_low is not null");
            return (Criteria) this;
        }

        public Criteria andDFinalLowEqualTo(Double value) {
            addCriterion("d_final_low =", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowNotEqualTo(Double value) {
            addCriterion("d_final_low <>", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowGreaterThan(Double value) {
            addCriterion("d_final_low >", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowGreaterThanOrEqualTo(Double value) {
            addCriterion("d_final_low >=", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowLessThan(Double value) {
            addCriterion("d_final_low <", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowLessThanOrEqualTo(Double value) {
            addCriterion("d_final_low <=", value, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowIn(List<Double> values) {
            addCriterion("d_final_low in", values, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowNotIn(List<Double> values) {
            addCriterion("d_final_low not in", values, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowBetween(Double value1, Double value2) {
            addCriterion("d_final_low between", value1, value2, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalLowNotBetween(Double value1, Double value2) {
            addCriterion("d_final_low not between", value1, value2, "dFinalLow");
            return (Criteria) this;
        }

        public Criteria andDFinalHighIsNull() {
            addCriterion("d_final_high is null");
            return (Criteria) this;
        }

        public Criteria andDFinalHighIsNotNull() {
            addCriterion("d_final_high is not null");
            return (Criteria) this;
        }

        public Criteria andDFinalHighEqualTo(Double value) {
            addCriterion("d_final_high =", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighNotEqualTo(Double value) {
            addCriterion("d_final_high <>", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighGreaterThan(Double value) {
            addCriterion("d_final_high >", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighGreaterThanOrEqualTo(Double value) {
            addCriterion("d_final_high >=", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighLessThan(Double value) {
            addCriterion("d_final_high <", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighLessThanOrEqualTo(Double value) {
            addCriterion("d_final_high <=", value, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighIn(List<Double> values) {
            addCriterion("d_final_high in", values, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighNotIn(List<Double> values) {
            addCriterion("d_final_high not in", values, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighBetween(Double value1, Double value2) {
            addCriterion("d_final_high between", value1, value2, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDFinalHighNotBetween(Double value1, Double value2) {
            addCriterion("d_final_high not between", value1, value2, "dFinalHigh");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgIsNull() {
            addCriterion("d_target_1_avg is null");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgIsNotNull() {
            addCriterion("d_target_1_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgEqualTo(Double value) {
            addCriterion("d_target_1_avg =", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgNotEqualTo(Double value) {
            addCriterion("d_target_1_avg <>", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgGreaterThan(Double value) {
            addCriterion("d_target_1_avg >", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_1_avg >=", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgLessThan(Double value) {
            addCriterion("d_target_1_avg <", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgLessThanOrEqualTo(Double value) {
            addCriterion("d_target_1_avg <=", value, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgIn(List<Double> values) {
            addCriterion("d_target_1_avg in", values, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgNotIn(List<Double> values) {
            addCriterion("d_target_1_avg not in", values, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgBetween(Double value1, Double value2) {
            addCriterion("d_target_1_avg between", value1, value2, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1AvgNotBetween(Double value1, Double value2) {
            addCriterion("d_target_1_avg not between", value1, value2, "dTarget1Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgIsNull() {
            addCriterion("d_target_2_avg is null");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgIsNotNull() {
            addCriterion("d_target_2_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgEqualTo(Double value) {
            addCriterion("d_target_2_avg =", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgNotEqualTo(Double value) {
            addCriterion("d_target_2_avg <>", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgGreaterThan(Double value) {
            addCriterion("d_target_2_avg >", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_2_avg >=", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgLessThan(Double value) {
            addCriterion("d_target_2_avg <", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgLessThanOrEqualTo(Double value) {
            addCriterion("d_target_2_avg <=", value, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgIn(List<Double> values) {
            addCriterion("d_target_2_avg in", values, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgNotIn(List<Double> values) {
            addCriterion("d_target_2_avg not in", values, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgBetween(Double value1, Double value2) {
            addCriterion("d_target_2_avg between", value1, value2, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget2AvgNotBetween(Double value1, Double value2) {
            addCriterion("d_target_2_avg not between", value1, value2, "dTarget2Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgIsNull() {
            addCriterion("d_target_3_avg is null");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgIsNotNull() {
            addCriterion("d_target_3_avg is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgEqualTo(Double value) {
            addCriterion("d_target_3_avg =", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgNotEqualTo(Double value) {
            addCriterion("d_target_3_avg <>", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgGreaterThan(Double value) {
            addCriterion("d_target_3_avg >", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_3_avg >=", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgLessThan(Double value) {
            addCriterion("d_target_3_avg <", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgLessThanOrEqualTo(Double value) {
            addCriterion("d_target_3_avg <=", value, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgIn(List<Double> values) {
            addCriterion("d_target_3_avg in", values, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgNotIn(List<Double> values) {
            addCriterion("d_target_3_avg not in", values, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgBetween(Double value1, Double value2) {
            addCriterion("d_target_3_avg between", value1, value2, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget3AvgNotBetween(Double value1, Double value2) {
            addCriterion("d_target_3_avg not between", value1, value2, "dTarget3Avg");
            return (Criteria) this;
        }

        public Criteria andDTarget1OIsNull() {
            addCriterion("d_target_1_o is null");
            return (Criteria) this;
        }

        public Criteria andDTarget1OIsNotNull() {
            addCriterion("d_target_1_o is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget1OEqualTo(Double value) {
            addCriterion("d_target_1_o =", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1ONotEqualTo(Double value) {
            addCriterion("d_target_1_o <>", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OGreaterThan(Double value) {
            addCriterion("d_target_1_o >", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_1_o >=", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OLessThan(Double value) {
            addCriterion("d_target_1_o <", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OLessThanOrEqualTo(Double value) {
            addCriterion("d_target_1_o <=", value, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OIn(List<Double> values) {
            addCriterion("d_target_1_o in", values, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1ONotIn(List<Double> values) {
            addCriterion("d_target_1_o not in", values, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1OBetween(Double value1, Double value2) {
            addCriterion("d_target_1_o between", value1, value2, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget1ONotBetween(Double value1, Double value2) {
            addCriterion("d_target_1_o not between", value1, value2, "dTarget1O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OIsNull() {
            addCriterion("d_target_2_o is null");
            return (Criteria) this;
        }

        public Criteria andDTarget2OIsNotNull() {
            addCriterion("d_target_2_o is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget2OEqualTo(Double value) {
            addCriterion("d_target_2_o =", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2ONotEqualTo(Double value) {
            addCriterion("d_target_2_o <>", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OGreaterThan(Double value) {
            addCriterion("d_target_2_o >", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_2_o >=", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OLessThan(Double value) {
            addCriterion("d_target_2_o <", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OLessThanOrEqualTo(Double value) {
            addCriterion("d_target_2_o <=", value, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OIn(List<Double> values) {
            addCriterion("d_target_2_o in", values, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2ONotIn(List<Double> values) {
            addCriterion("d_target_2_o not in", values, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2OBetween(Double value1, Double value2) {
            addCriterion("d_target_2_o between", value1, value2, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget2ONotBetween(Double value1, Double value2) {
            addCriterion("d_target_2_o not between", value1, value2, "dTarget2O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OIsNull() {
            addCriterion("d_target_3_o is null");
            return (Criteria) this;
        }

        public Criteria andDTarget3OIsNotNull() {
            addCriterion("d_target_3_o is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget3OEqualTo(Double value) {
            addCriterion("d_target_3_o =", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3ONotEqualTo(Double value) {
            addCriterion("d_target_3_o <>", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OGreaterThan(Double value) {
            addCriterion("d_target_3_o >", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_3_o >=", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OLessThan(Double value) {
            addCriterion("d_target_3_o <", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OLessThanOrEqualTo(Double value) {
            addCriterion("d_target_3_o <=", value, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OIn(List<Double> values) {
            addCriterion("d_target_3_o in", values, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3ONotIn(List<Double> values) {
            addCriterion("d_target_3_o not in", values, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3OBetween(Double value1, Double value2) {
            addCriterion("d_target_3_o between", value1, value2, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTarget3ONotBetween(Double value1, Double value2) {
            addCriterion("d_target_3_o not between", value1, value2, "dTarget3O");
            return (Criteria) this;
        }

        public Criteria andDTotalOIsNull() {
            addCriterion("d_total_o is null");
            return (Criteria) this;
        }

        public Criteria andDTotalOIsNotNull() {
            addCriterion("d_total_o is not null");
            return (Criteria) this;
        }

        public Criteria andDTotalOEqualTo(Double value) {
            addCriterion("d_total_o =", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalONotEqualTo(Double value) {
            addCriterion("d_total_o <>", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOGreaterThan(Double value) {
            addCriterion("d_total_o >", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOGreaterThanOrEqualTo(Double value) {
            addCriterion("d_total_o >=", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOLessThan(Double value) {
            addCriterion("d_total_o <", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOLessThanOrEqualTo(Double value) {
            addCriterion("d_total_o <=", value, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOIn(List<Double> values) {
            addCriterion("d_total_o in", values, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalONotIn(List<Double> values) {
            addCriterion("d_total_o not in", values, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalOBetween(Double value1, Double value2) {
            addCriterion("d_total_o between", value1, value2, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTotalONotBetween(Double value1, Double value2) {
            addCriterion("d_total_o not between", value1, value2, "dTotalO");
            return (Criteria) this;
        }

        public Criteria andDTarget1FIsNull() {
            addCriterion("d_target_1_f is null");
            return (Criteria) this;
        }

        public Criteria andDTarget1FIsNotNull() {
            addCriterion("d_target_1_f is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget1FEqualTo(Double value) {
            addCriterion("d_target_1_f =", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FNotEqualTo(Double value) {
            addCriterion("d_target_1_f <>", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FGreaterThan(Double value) {
            addCriterion("d_target_1_f >", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_1_f >=", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FLessThan(Double value) {
            addCriterion("d_target_1_f <", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FLessThanOrEqualTo(Double value) {
            addCriterion("d_target_1_f <=", value, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FIn(List<Double> values) {
            addCriterion("d_target_1_f in", values, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FNotIn(List<Double> values) {
            addCriterion("d_target_1_f not in", values, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FBetween(Double value1, Double value2) {
            addCriterion("d_target_1_f between", value1, value2, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget1FNotBetween(Double value1, Double value2) {
            addCriterion("d_target_1_f not between", value1, value2, "dTarget1F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FIsNull() {
            addCriterion("d_target_2_f is null");
            return (Criteria) this;
        }

        public Criteria andDTarget2FIsNotNull() {
            addCriterion("d_target_2_f is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget2FEqualTo(Double value) {
            addCriterion("d_target_2_f =", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FNotEqualTo(Double value) {
            addCriterion("d_target_2_f <>", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FGreaterThan(Double value) {
            addCriterion("d_target_2_f >", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_2_f >=", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FLessThan(Double value) {
            addCriterion("d_target_2_f <", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FLessThanOrEqualTo(Double value) {
            addCriterion("d_target_2_f <=", value, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FIn(List<Double> values) {
            addCriterion("d_target_2_f in", values, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FNotIn(List<Double> values) {
            addCriterion("d_target_2_f not in", values, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FBetween(Double value1, Double value2) {
            addCriterion("d_target_2_f between", value1, value2, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget2FNotBetween(Double value1, Double value2) {
            addCriterion("d_target_2_f not between", value1, value2, "dTarget2F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FIsNull() {
            addCriterion("d_target_3_f is null");
            return (Criteria) this;
        }

        public Criteria andDTarget3FIsNotNull() {
            addCriterion("d_target_3_f is not null");
            return (Criteria) this;
        }

        public Criteria andDTarget3FEqualTo(Double value) {
            addCriterion("d_target_3_f =", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FNotEqualTo(Double value) {
            addCriterion("d_target_3_f <>", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FGreaterThan(Double value) {
            addCriterion("d_target_3_f >", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FGreaterThanOrEqualTo(Double value) {
            addCriterion("d_target_3_f >=", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FLessThan(Double value) {
            addCriterion("d_target_3_f <", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FLessThanOrEqualTo(Double value) {
            addCriterion("d_target_3_f <=", value, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FIn(List<Double> values) {
            addCriterion("d_target_3_f in", values, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FNotIn(List<Double> values) {
            addCriterion("d_target_3_f not in", values, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FBetween(Double value1, Double value2) {
            addCriterion("d_target_3_f between", value1, value2, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTarget3FNotBetween(Double value1, Double value2) {
            addCriterion("d_target_3_f not between", value1, value2, "dTarget3F");
            return (Criteria) this;
        }

        public Criteria andDTotalFIsNull() {
            addCriterion("d_total_f is null");
            return (Criteria) this;
        }

        public Criteria andDTotalFIsNotNull() {
            addCriterion("d_total_f is not null");
            return (Criteria) this;
        }

        public Criteria andDTotalFEqualTo(Double value) {
            addCriterion("d_total_f =", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFNotEqualTo(Double value) {
            addCriterion("d_total_f <>", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFGreaterThan(Double value) {
            addCriterion("d_total_f >", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFGreaterThanOrEqualTo(Double value) {
            addCriterion("d_total_f >=", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFLessThan(Double value) {
            addCriterion("d_total_f <", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFLessThanOrEqualTo(Double value) {
            addCriterion("d_total_f <=", value, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFIn(List<Double> values) {
            addCriterion("d_total_f in", values, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFNotIn(List<Double> values) {
            addCriterion("d_total_f not in", values, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFBetween(Double value1, Double value2) {
            addCriterion("d_total_f between", value1, value2, "dTotalF");
            return (Criteria) this;
        }

        public Criteria andDTotalFNotBetween(Double value1, Double value2) {
            addCriterion("d_total_f not between", value1, value2, "dTotalF");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class_degree
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 23 21:25:57 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class_degree
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}