package com.school.course_achievement.pojo;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.k_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String kNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.k_name
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String kName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.k_target1
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String kTarget1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.k_target2
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String kTarget2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.k_target3
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String kTarget3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.t_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    private String tNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.k_no
     *
     * @return the value of course.k_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String getkNo() {
        return kNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.k_no
     *
     * @param kNo the value for course.k_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void setkNo(String kNo) {
        this.kNo = kNo == null ? null : kNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.k_name
     *
     * @return the value of course.k_name
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String getkName() {
        return kName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.k_name
     *
     * @param kName the value for course.k_name
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void setkName(String kName) {
        this.kName = kName == null ? null : kName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.k_target1
     *
     * @return the value of course.k_target1
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String getkTarget1() {
        return kTarget1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.k_target1
     *
     * @param kTarget1 the value for course.k_target1
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void setkTarget1(String kTarget1) {
        this.kTarget1 = kTarget1 == null ? null : kTarget1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.k_target2
     *
     * @return the value of course.k_target2
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String getkTarget2() {
        return kTarget2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.k_target2
     *
     * @param kTarget2 the value for course.k_target2
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void setkTarget2(String kTarget2) {
        this.kTarget2 = kTarget2 == null ? null : kTarget2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.k_target3
     *
     * @return the value of course.k_target3
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String getkTarget3() {
        return kTarget3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.k_target3
     *
     * @param kTarget3 the value for course.k_target3
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void setkTarget3(String kTarget3) {
        this.kTarget3 = kTarget3 == null ? null : kTarget3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.t_no
     *
     * @return the value of course.t_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public String gettNo() {
        return tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.t_no
     *
     * @param tNo the value for course.t_no
     *
     * @mbggenerated Thu Oct 20 10:15:55 CST 2022
     */
    public void settNo(String tNo) {
        this.tNo = tNo == null ? null : tNo.trim();
    }
}