package com.school.course_achievement.pojo;

public class GraduateRequirement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_requirement.r_id
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_requirement.r_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private String rContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column graduate_requirement.p_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private String pContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_requirement.r_id
     *
     * @return the value of graduate_requirement.r_id
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_requirement.r_id
     *
     * @param rId the value for graduate_requirement.r_id
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_requirement.r_content
     *
     * @return the value of graduate_requirement.r_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getrContent() {
        return rContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_requirement.r_content
     *
     * @param rContent the value for graduate_requirement.r_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setrContent(String rContent) {
        this.rContent = rContent == null ? null : rContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column graduate_requirement.p_content
     *
     * @return the value of graduate_requirement.p_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getpContent() {
        return pContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column graduate_requirement.p_content
     *
     * @param pContent the value for graduate_requirement.p_content
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setpContent(String pContent) {
        this.pContent = pContent == null ? null : pContent.trim();
    }
}