package com.school.course_achievement.pojo;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private String sNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.c_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    private String cNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_no
     *
     * @return the value of student.s_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_no
     *
     * @param sNo the value for student.s_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setsNo(String sNo) {
        this.sNo = sNo == null ? null : sNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.c_no
     *
     * @return the value of student.c_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.c_no
     *
     * @param cNo the value for student.c_no
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }
}