package com.school.course_achievement.pojo;

public class StudentDegree extends StudentDegreeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.behave_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double behaveDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.homework_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double homeworkDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.test_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double testDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.final_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double finalDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.target_1_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double target1Degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.target_2_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double target2Degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_degree.target_3_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    private Double target3Degree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.behave_degree
     *
     * @return the value of student_degree.behave_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getBehaveDegree() {
        return behaveDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.behave_degree
     *
     * @param behaveDegree the value for student_degree.behave_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setBehaveDegree(Double behaveDegree) {
        this.behaveDegree = behaveDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.homework_degree
     *
     * @return the value of student_degree.homework_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getHomeworkDegree() {
        return homeworkDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.homework_degree
     *
     * @param homeworkDegree the value for student_degree.homework_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setHomeworkDegree(Double homeworkDegree) {
        this.homeworkDegree = homeworkDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.test_degree
     *
     * @return the value of student_degree.test_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getTestDegree() {
        return testDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.test_degree
     *
     * @param testDegree the value for student_degree.test_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setTestDegree(Double testDegree) {
        this.testDegree = testDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.final_degree
     *
     * @return the value of student_degree.final_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getFinalDegree() {
        return finalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.final_degree
     *
     * @param finalDegree the value for student_degree.final_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setFinalDegree(Double finalDegree) {
        this.finalDegree = finalDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.target_1_degree
     *
     * @return the value of student_degree.target_1_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getTarget1Degree() {
        return target1Degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.target_1_degree
     *
     * @param target1Degree the value for student_degree.target_1_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setTarget1Degree(Double target1Degree) {
        this.target1Degree = target1Degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.target_2_degree
     *
     * @return the value of student_degree.target_2_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getTarget2Degree() {
        return target2Degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.target_2_degree
     *
     * @param target2Degree the value for student_degree.target_2_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setTarget2Degree(Double target2Degree) {
        this.target2Degree = target2Degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_degree.target_3_degree
     *
     * @return the value of student_degree.target_3_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public Double getTarget3Degree() {
        return target3Degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_degree.target_3_degree
     *
     * @param target3Degree the value for student_degree.target_3_degree
     *
     * @mbggenerated Tue Oct 25 14:09:53 CST 2022
     */
    public void setTarget3Degree(Double target3Degree) {
        this.target3Degree = target3Degree;
    }
}