package com.school.course_achievement.pojo;

public class Weight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.k_no
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private String kNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.behave_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double behaveTarget1Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.behave_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double behaveTarget2Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.behave_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double behaveTarget3Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.homework_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double homeworkTarget1Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.homework_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double homeworkTarget2Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.homework_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double homeworkTarget3Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.test_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double testTarget1Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.test_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double testTarget2Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.test_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double testTarget3Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.final_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double finalTarget1Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.final_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double finalTarget2Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.final_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double finalTarget3Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.total_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double totalTarget1Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.total_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double totalTarget2Weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weight.total_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    private Double totalTarget3Weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.k_no
     *
     * @return the value of weight.k_no
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public String getkNo() {
        return kNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.k_no
     *
     * @param kNo the value for weight.k_no
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setkNo(String kNo) {
        this.kNo = kNo == null ? null : kNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.behave_target_1_weight
     *
     * @return the value of weight.behave_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getBehaveTarget1Weight() {
        return behaveTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.behave_target_1_weight
     *
     * @param behaveTarget1Weight the value for weight.behave_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setBehaveTarget1Weight(Double behaveTarget1Weight) {
        this.behaveTarget1Weight = behaveTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.behave_target_2_weight
     *
     * @return the value of weight.behave_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getBehaveTarget2Weight() {
        return behaveTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.behave_target_2_weight
     *
     * @param behaveTarget2Weight the value for weight.behave_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setBehaveTarget2Weight(Double behaveTarget2Weight) {
        this.behaveTarget2Weight = behaveTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.behave_target_3_weight
     *
     * @return the value of weight.behave_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getBehaveTarget3Weight() {
        return behaveTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.behave_target_3_weight
     *
     * @param behaveTarget3Weight the value for weight.behave_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setBehaveTarget3Weight(Double behaveTarget3Weight) {
        this.behaveTarget3Weight = behaveTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.homework_target_1_weight
     *
     * @return the value of weight.homework_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getHomeworkTarget1Weight() {
        return homeworkTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.homework_target_1_weight
     *
     * @param homeworkTarget1Weight the value for weight.homework_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setHomeworkTarget1Weight(Double homeworkTarget1Weight) {
        this.homeworkTarget1Weight = homeworkTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.homework_target_2_weight
     *
     * @return the value of weight.homework_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getHomeworkTarget2Weight() {
        return homeworkTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.homework_target_2_weight
     *
     * @param homeworkTarget2Weight the value for weight.homework_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setHomeworkTarget2Weight(Double homeworkTarget2Weight) {
        this.homeworkTarget2Weight = homeworkTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.homework_target_3_weight
     *
     * @return the value of weight.homework_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getHomeworkTarget3Weight() {
        return homeworkTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.homework_target_3_weight
     *
     * @param homeworkTarget3Weight the value for weight.homework_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setHomeworkTarget3Weight(Double homeworkTarget3Weight) {
        this.homeworkTarget3Weight = homeworkTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.test_target_1_weight
     *
     * @return the value of weight.test_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTestTarget1Weight() {
        return testTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.test_target_1_weight
     *
     * @param testTarget1Weight the value for weight.test_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTestTarget1Weight(Double testTarget1Weight) {
        this.testTarget1Weight = testTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.test_target_2_weight
     *
     * @return the value of weight.test_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTestTarget2Weight() {
        return testTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.test_target_2_weight
     *
     * @param testTarget2Weight the value for weight.test_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTestTarget2Weight(Double testTarget2Weight) {
        this.testTarget2Weight = testTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.test_target_3_weight
     *
     * @return the value of weight.test_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTestTarget3Weight() {
        return testTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.test_target_3_weight
     *
     * @param testTarget3Weight the value for weight.test_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTestTarget3Weight(Double testTarget3Weight) {
        this.testTarget3Weight = testTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.final_target_1_weight
     *
     * @return the value of weight.final_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getFinalTarget1Weight() {
        return finalTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.final_target_1_weight
     *
     * @param finalTarget1Weight the value for weight.final_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setFinalTarget1Weight(Double finalTarget1Weight) {
        this.finalTarget1Weight = finalTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.final_target_2_weight
     *
     * @return the value of weight.final_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getFinalTarget2Weight() {
        return finalTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.final_target_2_weight
     *
     * @param finalTarget2Weight the value for weight.final_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setFinalTarget2Weight(Double finalTarget2Weight) {
        this.finalTarget2Weight = finalTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.final_target_3_weight
     *
     * @return the value of weight.final_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getFinalTarget3Weight() {
        return finalTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.final_target_3_weight
     *
     * @param finalTarget3Weight the value for weight.final_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setFinalTarget3Weight(Double finalTarget3Weight) {
        this.finalTarget3Weight = finalTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.total_target_1_weight
     *
     * @return the value of weight.total_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTotalTarget1Weight() {
        return totalTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.total_target_1_weight
     *
     * @param totalTarget1Weight the value for weight.total_target_1_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTotalTarget1Weight(Double totalTarget1Weight) {
        this.totalTarget1Weight = totalTarget1Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.total_target_2_weight
     *
     * @return the value of weight.total_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTotalTarget2Weight() {
        return totalTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.total_target_2_weight
     *
     * @param totalTarget2Weight the value for weight.total_target_2_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTotalTarget2Weight(Double totalTarget2Weight) {
        this.totalTarget2Weight = totalTarget2Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weight.total_target_3_weight
     *
     * @return the value of weight.total_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public Double getTotalTarget3Weight() {
        return totalTarget3Weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weight.total_target_3_weight
     *
     * @param totalTarget3Weight the value for weight.total_target_3_weight
     *
     * @mbggenerated Sat Oct 29 21:39:18 CST 2022
     */
    public void setTotalTarget3Weight(Double totalTarget3Weight) {
        this.totalTarget3Weight = totalTarget3Weight;
    }
}