package com.school.course_achievement.pojo;

import java.util.ArrayList;
import java.util.List;

public class WeightExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public WeightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKNoIsNull() {
            addCriterion("k_no is null");
            return (Criteria) this;
        }

        public Criteria andKNoIsNotNull() {
            addCriterion("k_no is not null");
            return (Criteria) this;
        }

        public Criteria andKNoEqualTo(String value) {
            addCriterion("k_no =", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotEqualTo(String value) {
            addCriterion("k_no <>", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoGreaterThan(String value) {
            addCriterion("k_no >", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoGreaterThanOrEqualTo(String value) {
            addCriterion("k_no >=", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLessThan(String value) {
            addCriterion("k_no <", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLessThanOrEqualTo(String value) {
            addCriterion("k_no <=", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoLike(String value) {
            addCriterion("k_no like", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotLike(String value) {
            addCriterion("k_no not like", value, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoIn(List<String> values) {
            addCriterion("k_no in", values, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotIn(List<String> values) {
            addCriterion("k_no not in", values, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoBetween(String value1, String value2) {
            addCriterion("k_no between", value1, value2, "kNo");
            return (Criteria) this;
        }

        public Criteria andKNoNotBetween(String value1, String value2) {
            addCriterion("k_no not between", value1, value2, "kNo");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightIsNull() {
            addCriterion("behave_target_1_weight is null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightIsNotNull() {
            addCriterion("behave_target_1_weight is not null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightEqualTo(Double value) {
            addCriterion("behave_target_1_weight =", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightNotEqualTo(Double value) {
            addCriterion("behave_target_1_weight <>", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightGreaterThan(Double value) {
            addCriterion("behave_target_1_weight >", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("behave_target_1_weight >=", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightLessThan(Double value) {
            addCriterion("behave_target_1_weight <", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightLessThanOrEqualTo(Double value) {
            addCriterion("behave_target_1_weight <=", value, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightIn(List<Double> values) {
            addCriterion("behave_target_1_weight in", values, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightNotIn(List<Double> values) {
            addCriterion("behave_target_1_weight not in", values, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightBetween(Double value1, Double value2) {
            addCriterion("behave_target_1_weight between", value1, value2, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget1WeightNotBetween(Double value1, Double value2) {
            addCriterion("behave_target_1_weight not between", value1, value2, "behaveTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightIsNull() {
            addCriterion("behave_target_2_weight is null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightIsNotNull() {
            addCriterion("behave_target_2_weight is not null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightEqualTo(Double value) {
            addCriterion("behave_target_2_weight =", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightNotEqualTo(Double value) {
            addCriterion("behave_target_2_weight <>", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightGreaterThan(Double value) {
            addCriterion("behave_target_2_weight >", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("behave_target_2_weight >=", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightLessThan(Double value) {
            addCriterion("behave_target_2_weight <", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightLessThanOrEqualTo(Double value) {
            addCriterion("behave_target_2_weight <=", value, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightIn(List<Double> values) {
            addCriterion("behave_target_2_weight in", values, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightNotIn(List<Double> values) {
            addCriterion("behave_target_2_weight not in", values, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightBetween(Double value1, Double value2) {
            addCriterion("behave_target_2_weight between", value1, value2, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget2WeightNotBetween(Double value1, Double value2) {
            addCriterion("behave_target_2_weight not between", value1, value2, "behaveTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightIsNull() {
            addCriterion("behave_target_3_weight is null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightIsNotNull() {
            addCriterion("behave_target_3_weight is not null");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightEqualTo(Double value) {
            addCriterion("behave_target_3_weight =", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightNotEqualTo(Double value) {
            addCriterion("behave_target_3_weight <>", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightGreaterThan(Double value) {
            addCriterion("behave_target_3_weight >", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("behave_target_3_weight >=", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightLessThan(Double value) {
            addCriterion("behave_target_3_weight <", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightLessThanOrEqualTo(Double value) {
            addCriterion("behave_target_3_weight <=", value, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightIn(List<Double> values) {
            addCriterion("behave_target_3_weight in", values, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightNotIn(List<Double> values) {
            addCriterion("behave_target_3_weight not in", values, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightBetween(Double value1, Double value2) {
            addCriterion("behave_target_3_weight between", value1, value2, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andBehaveTarget3WeightNotBetween(Double value1, Double value2) {
            addCriterion("behave_target_3_weight not between", value1, value2, "behaveTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightIsNull() {
            addCriterion("homework_target_1_weight is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightIsNotNull() {
            addCriterion("homework_target_1_weight is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightEqualTo(Double value) {
            addCriterion("homework_target_1_weight =", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightNotEqualTo(Double value) {
            addCriterion("homework_target_1_weight <>", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightGreaterThan(Double value) {
            addCriterion("homework_target_1_weight >", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("homework_target_1_weight >=", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightLessThan(Double value) {
            addCriterion("homework_target_1_weight <", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightLessThanOrEqualTo(Double value) {
            addCriterion("homework_target_1_weight <=", value, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightIn(List<Double> values) {
            addCriterion("homework_target_1_weight in", values, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightNotIn(List<Double> values) {
            addCriterion("homework_target_1_weight not in", values, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightBetween(Double value1, Double value2) {
            addCriterion("homework_target_1_weight between", value1, value2, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget1WeightNotBetween(Double value1, Double value2) {
            addCriterion("homework_target_1_weight not between", value1, value2, "homeworkTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightIsNull() {
            addCriterion("homework_target_2_weight is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightIsNotNull() {
            addCriterion("homework_target_2_weight is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightEqualTo(Double value) {
            addCriterion("homework_target_2_weight =", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightNotEqualTo(Double value) {
            addCriterion("homework_target_2_weight <>", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightGreaterThan(Double value) {
            addCriterion("homework_target_2_weight >", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("homework_target_2_weight >=", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightLessThan(Double value) {
            addCriterion("homework_target_2_weight <", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightLessThanOrEqualTo(Double value) {
            addCriterion("homework_target_2_weight <=", value, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightIn(List<Double> values) {
            addCriterion("homework_target_2_weight in", values, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightNotIn(List<Double> values) {
            addCriterion("homework_target_2_weight not in", values, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightBetween(Double value1, Double value2) {
            addCriterion("homework_target_2_weight between", value1, value2, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget2WeightNotBetween(Double value1, Double value2) {
            addCriterion("homework_target_2_weight not between", value1, value2, "homeworkTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightIsNull() {
            addCriterion("homework_target_3_weight is null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightIsNotNull() {
            addCriterion("homework_target_3_weight is not null");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightEqualTo(Double value) {
            addCriterion("homework_target_3_weight =", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightNotEqualTo(Double value) {
            addCriterion("homework_target_3_weight <>", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightGreaterThan(Double value) {
            addCriterion("homework_target_3_weight >", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("homework_target_3_weight >=", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightLessThan(Double value) {
            addCriterion("homework_target_3_weight <", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightLessThanOrEqualTo(Double value) {
            addCriterion("homework_target_3_weight <=", value, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightIn(List<Double> values) {
            addCriterion("homework_target_3_weight in", values, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightNotIn(List<Double> values) {
            addCriterion("homework_target_3_weight not in", values, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightBetween(Double value1, Double value2) {
            addCriterion("homework_target_3_weight between", value1, value2, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andHomeworkTarget3WeightNotBetween(Double value1, Double value2) {
            addCriterion("homework_target_3_weight not between", value1, value2, "homeworkTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightIsNull() {
            addCriterion("test_target_1_weight is null");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightIsNotNull() {
            addCriterion("test_target_1_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightEqualTo(Double value) {
            addCriterion("test_target_1_weight =", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightNotEqualTo(Double value) {
            addCriterion("test_target_1_weight <>", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightGreaterThan(Double value) {
            addCriterion("test_target_1_weight >", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("test_target_1_weight >=", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightLessThan(Double value) {
            addCriterion("test_target_1_weight <", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightLessThanOrEqualTo(Double value) {
            addCriterion("test_target_1_weight <=", value, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightIn(List<Double> values) {
            addCriterion("test_target_1_weight in", values, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightNotIn(List<Double> values) {
            addCriterion("test_target_1_weight not in", values, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightBetween(Double value1, Double value2) {
            addCriterion("test_target_1_weight between", value1, value2, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget1WeightNotBetween(Double value1, Double value2) {
            addCriterion("test_target_1_weight not between", value1, value2, "testTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightIsNull() {
            addCriterion("test_target_2_weight is null");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightIsNotNull() {
            addCriterion("test_target_2_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightEqualTo(Double value) {
            addCriterion("test_target_2_weight =", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightNotEqualTo(Double value) {
            addCriterion("test_target_2_weight <>", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightGreaterThan(Double value) {
            addCriterion("test_target_2_weight >", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("test_target_2_weight >=", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightLessThan(Double value) {
            addCriterion("test_target_2_weight <", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightLessThanOrEqualTo(Double value) {
            addCriterion("test_target_2_weight <=", value, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightIn(List<Double> values) {
            addCriterion("test_target_2_weight in", values, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightNotIn(List<Double> values) {
            addCriterion("test_target_2_weight not in", values, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightBetween(Double value1, Double value2) {
            addCriterion("test_target_2_weight between", value1, value2, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget2WeightNotBetween(Double value1, Double value2) {
            addCriterion("test_target_2_weight not between", value1, value2, "testTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightIsNull() {
            addCriterion("test_target_3_weight is null");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightIsNotNull() {
            addCriterion("test_target_3_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightEqualTo(Double value) {
            addCriterion("test_target_3_weight =", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightNotEqualTo(Double value) {
            addCriterion("test_target_3_weight <>", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightGreaterThan(Double value) {
            addCriterion("test_target_3_weight >", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("test_target_3_weight >=", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightLessThan(Double value) {
            addCriterion("test_target_3_weight <", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightLessThanOrEqualTo(Double value) {
            addCriterion("test_target_3_weight <=", value, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightIn(List<Double> values) {
            addCriterion("test_target_3_weight in", values, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightNotIn(List<Double> values) {
            addCriterion("test_target_3_weight not in", values, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightBetween(Double value1, Double value2) {
            addCriterion("test_target_3_weight between", value1, value2, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTestTarget3WeightNotBetween(Double value1, Double value2) {
            addCriterion("test_target_3_weight not between", value1, value2, "testTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightIsNull() {
            addCriterion("final_target_1_weight is null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightIsNotNull() {
            addCriterion("final_target_1_weight is not null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightEqualTo(Double value) {
            addCriterion("final_target_1_weight =", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightNotEqualTo(Double value) {
            addCriterion("final_target_1_weight <>", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightGreaterThan(Double value) {
            addCriterion("final_target_1_weight >", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("final_target_1_weight >=", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightLessThan(Double value) {
            addCriterion("final_target_1_weight <", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightLessThanOrEqualTo(Double value) {
            addCriterion("final_target_1_weight <=", value, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightIn(List<Double> values) {
            addCriterion("final_target_1_weight in", values, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightNotIn(List<Double> values) {
            addCriterion("final_target_1_weight not in", values, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightBetween(Double value1, Double value2) {
            addCriterion("final_target_1_weight between", value1, value2, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget1WeightNotBetween(Double value1, Double value2) {
            addCriterion("final_target_1_weight not between", value1, value2, "finalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightIsNull() {
            addCriterion("final_target_2_weight is null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightIsNotNull() {
            addCriterion("final_target_2_weight is not null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightEqualTo(Double value) {
            addCriterion("final_target_2_weight =", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightNotEqualTo(Double value) {
            addCriterion("final_target_2_weight <>", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightGreaterThan(Double value) {
            addCriterion("final_target_2_weight >", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("final_target_2_weight >=", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightLessThan(Double value) {
            addCriterion("final_target_2_weight <", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightLessThanOrEqualTo(Double value) {
            addCriterion("final_target_2_weight <=", value, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightIn(List<Double> values) {
            addCriterion("final_target_2_weight in", values, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightNotIn(List<Double> values) {
            addCriterion("final_target_2_weight not in", values, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightBetween(Double value1, Double value2) {
            addCriterion("final_target_2_weight between", value1, value2, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget2WeightNotBetween(Double value1, Double value2) {
            addCriterion("final_target_2_weight not between", value1, value2, "finalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightIsNull() {
            addCriterion("final_target_3_weight is null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightIsNotNull() {
            addCriterion("final_target_3_weight is not null");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightEqualTo(Double value) {
            addCriterion("final_target_3_weight =", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightNotEqualTo(Double value) {
            addCriterion("final_target_3_weight <>", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightGreaterThan(Double value) {
            addCriterion("final_target_3_weight >", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("final_target_3_weight >=", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightLessThan(Double value) {
            addCriterion("final_target_3_weight <", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightLessThanOrEqualTo(Double value) {
            addCriterion("final_target_3_weight <=", value, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightIn(List<Double> values) {
            addCriterion("final_target_3_weight in", values, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightNotIn(List<Double> values) {
            addCriterion("final_target_3_weight not in", values, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightBetween(Double value1, Double value2) {
            addCriterion("final_target_3_weight between", value1, value2, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andFinalTarget3WeightNotBetween(Double value1, Double value2) {
            addCriterion("final_target_3_weight not between", value1, value2, "finalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightIsNull() {
            addCriterion("total_target_1_weight is null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightIsNotNull() {
            addCriterion("total_target_1_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightEqualTo(Double value) {
            addCriterion("total_target_1_weight =", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightNotEqualTo(Double value) {
            addCriterion("total_target_1_weight <>", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightGreaterThan(Double value) {
            addCriterion("total_target_1_weight >", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("total_target_1_weight >=", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightLessThan(Double value) {
            addCriterion("total_target_1_weight <", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightLessThanOrEqualTo(Double value) {
            addCriterion("total_target_1_weight <=", value, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightIn(List<Double> values) {
            addCriterion("total_target_1_weight in", values, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightNotIn(List<Double> values) {
            addCriterion("total_target_1_weight not in", values, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightBetween(Double value1, Double value2) {
            addCriterion("total_target_1_weight between", value1, value2, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget1WeightNotBetween(Double value1, Double value2) {
            addCriterion("total_target_1_weight not between", value1, value2, "totalTarget1Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightIsNull() {
            addCriterion("total_target_2_weight is null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightIsNotNull() {
            addCriterion("total_target_2_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightEqualTo(Double value) {
            addCriterion("total_target_2_weight =", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightNotEqualTo(Double value) {
            addCriterion("total_target_2_weight <>", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightGreaterThan(Double value) {
            addCriterion("total_target_2_weight >", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("total_target_2_weight >=", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightLessThan(Double value) {
            addCriterion("total_target_2_weight <", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightLessThanOrEqualTo(Double value) {
            addCriterion("total_target_2_weight <=", value, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightIn(List<Double> values) {
            addCriterion("total_target_2_weight in", values, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightNotIn(List<Double> values) {
            addCriterion("total_target_2_weight not in", values, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightBetween(Double value1, Double value2) {
            addCriterion("total_target_2_weight between", value1, value2, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget2WeightNotBetween(Double value1, Double value2) {
            addCriterion("total_target_2_weight not between", value1, value2, "totalTarget2Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightIsNull() {
            addCriterion("total_target_3_weight is null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightIsNotNull() {
            addCriterion("total_target_3_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightEqualTo(Double value) {
            addCriterion("total_target_3_weight =", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightNotEqualTo(Double value) {
            addCriterion("total_target_3_weight <>", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightGreaterThan(Double value) {
            addCriterion("total_target_3_weight >", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightGreaterThanOrEqualTo(Double value) {
            addCriterion("total_target_3_weight >=", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightLessThan(Double value) {
            addCriterion("total_target_3_weight <", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightLessThanOrEqualTo(Double value) {
            addCriterion("total_target_3_weight <=", value, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightIn(List<Double> values) {
            addCriterion("total_target_3_weight in", values, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightNotIn(List<Double> values) {
            addCriterion("total_target_3_weight not in", values, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightBetween(Double value1, Double value2) {
            addCriterion("total_target_3_weight between", value1, value2, "totalTarget3Weight");
            return (Criteria) this;
        }

        public Criteria andTotalTarget3WeightNotBetween(Double value1, Double value2) {
            addCriterion("total_target_3_weight not between", value1, value2, "totalTarget3Weight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weight
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 23 21:25:57 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weight
     *
     * @mbggenerated Sun Oct 23 21:25:57 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}